name: pull-request-main
on:
  pull_request:
    branches:
      - main
    types: [opened, edited, synchronize]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1