name: pull-request-main
on:
  pull_request:
    branches:
      - main
    types: [opened, edited]
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: bcoe/conventional-release-labels@v1
        with:
          type_labels: {"feat": "feature", "fix": "fix", "breaking": "breaking","ci":"ci","docs":"docs"}
