name: Test get latest RC
on: push

jobs:
  get_draft:
    name: Get latest pre-release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: "call action"
        id: last_release
        uses: InsonusK/get-latest-release@v1.0
        with:
          myToken: ${{ github.token }}
          exclude_types: "release"
      - name: "Print result"
        run: |
          echo "id: ${{ steps.last_release.outputs.id }}"
          echo "tag_name: ${{ steps.last_release.outputs.tag_name }}"
          echo "created_at: ${{ steps.last_release.outputs.created_atd }}"
          echo "draft: ${{ steps.last_release.outputs.draft }}"
          echo "prerelease: ${{ steps.last_release.outputs.prerelease }}"
